all:
	gcc parent.c -o parent
	gcc child.c -o child
clean:
	rm -rf parent child CHILD_W CHILD_R Child_1_W Child_1_R Child_2_W Child_2_R Child_3_W Child_3_R Child_4_W Child_4_R Child_5_W Child_5_R
new:
	make clean all 
	./parent